-- Run this script in the Supabase SQL Editor to add the missing internal notes

UPDATE public.mensajes SET internal_note = 'Recordar que Guápiles y Liberia NO son Sedes, son Centros de Atención Estudiantil, y así debe explicarse al estudiante. Salvedad: en los cursos con laboratorio deben desplazarse a Sede Central, San José o Liberia, y llenar el formulario correspondiente.' WHERE title = 'Carreras aprobadas en la sede';
UPDATE public.mensajes SET internal_note = 'Agregar este texto a continuación de D04 únicamente si la carrera consultada incluye cursos con laboratorio.' WHERE title = 'Complemento: carrera con laboratorios';
UPDATE public.mensajes SET internal_note = 'Actualizar las fechas en verde cada cuatrimestre.' WHERE title = 'Matrícula ordinaria — nuevo ingreso o reingreso';
UPDATE public.mensajes SET internal_note = 'Aplica solo si el estudiante no ha cursado 2 sesiones de clase, es decir, si únicamente perdió 1 lección.' WHERE title = 'Matrícula súper extraordinaria (con recargo)';
UPDATE public.mensajes SET internal_note = 'Actualizar el cuatrimestre y las fechas de pago (en verde) cada término.' WHERE title = 'Beneficios del financiamiento y fechas de pago';
UPDATE public.mensajes SET internal_note = 'Si el prospecto responde afirmativamente (ej. "sí", "dale") sin especificar cantidad de materias ni forma de pago, continuá con esta plantilla y luego pasá a D15 solicitando esos dos datos antes de dar montos.' WHERE title = 'Si manifiesta interés en matricular';
UPDATE public.mensajes SET internal_note = 'Completar únicamente después de tener la cantidad de materias y la forma de pago (financiamiento o contado) elegida por el prospecto. Si no las indicó, solicitáselas antes de enviar montos.' WHERE title = 'Detalle de montos (servicio al cliente contesta)';
UPDATE public.mensajes SET internal_note = 'Aplica para nuevo ingreso, reingreso y estudiante activo/regular de la Maestría en Ingeniería Ambiental.' WHERE title = 'Costo Maestría — todas las modalidades';
UPDATE public.mensajes SET internal_note = 'Indicar siempre al estudiante que debe incluir nombre completo, número de identificación y trámite por el cual se realiza el pago.' WHERE title = 'Correo de reporte de pagos — Sede San Carlos';
UPDATE public.mensajes SET internal_note = 'Los requisitos formales se solicitan solo cuando el estudiante decida avanzar (con o sin preestudio previo).' WHERE title = 'Convalidación de estudios';
UPDATE public.mensajes SET internal_note = 'Verificar en Acamsys que el plan de estudios esté "concluido" o "concluyendo" antes de indicar este trámite. Si el estudiante desea ingresar a la Licenciatura, debe cancelar primero los derechos de graduación de Bachillerato (Ingeniería Civil o Industrial).' WHERE title = 'Derechos de graduación';
UPDATE public.mensajes SET internal_note = 'Este mensaje lo envía el personal de Ventas cuando el prospecto ya está listo para formalizar. Incluir el link del formulario de la sede correspondiente, según lo indicado por TI.' WHERE title = 'Envío de requisitos — lo redacta Ventas';
UPDATE public.mensajes SET internal_note = 'Se envía por correo una vez que el prospecto llenó el formulario. Pedirle que devuelva el correo firmado. El punto sobre laboratorios solo aplica si la carrera los incluye.
Asunto sugerido: ¡Asegura tu lugar hoy y vive una experiencia extraordinaria en la UIN!' WHERE title = 'Correo de pre-matrícula — lo redacta Registro y Plataforma';
UPDATE public.mensajes SET internal_note = 'Enviar una vez confirmado el pago y formalizada la matrícula. Recordar generar la contraseña del estudiante en Acamsys.
Asunto sugerido: ¡Bienvenid@ a la UIN! Tu matrícula está lista para un cuatrimestre extraordinario' WHERE title = 'Correo de bienvenida tras confirmar el pago';
